# Generated by Django 3.2.12 on 2022-04-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20220412_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='auth.user'),
        ),
    ]
