# Generated by Django 3.2.12 on 2022-04-12 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_alter_rule_plan'),
        ('users', '0003_alter_usermanager_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserManager',
            new_name='UserMeta',
        ),
    ]
