# Generated by Django 3.2.12 on 2022-04-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='action',
            new_name='resource',
        ),
    ]
