# Generated by Django 3.2.12 on 2022-04-14 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='active_period',
        ),
        migrations.AddField(
            model_name='planlog',
            name='active_period',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
