# Generated by Django 3.2.12 on 2022-04-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_action_rule_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='rule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule', to='company.rule'),
        ),
    ]
