# Generated by Django 3.2.12 on 2022-04-14 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220414_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlog',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
