# Generated by Django 3.2.12 on 2022-04-14 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_alter_planlog_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('access_date', models.DateField(blank=True, default=datetime.datetime(2022, 4, 14, 14, 9, 34, 315851, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requestlog_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
