# Generated by Django 3.2.12 on 2022-04-14 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='access_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
