# Generated by Django 3.2.12 on 2022-04-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220412_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plan_rules_set', to='company.plan'),
            preserve_default=False,
        ),
    ]
