# Generated by Django 3.2.12 on 2022-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_requestlog_access_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='resource',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('plan', 'resource')},
        ),
    ]
