# Generated by Django 3.2.12 on 2022-04-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_requestlog_plan_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='plan_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_log_requestlog_set', to='company.planlog'),
        ),
    ]
