# Generated by Django 3.2.12 on 2022-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_requestlog_plan_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='count_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='count_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
