# Generated by Django 3.2.12 on 2022-04-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20220419_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlog',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_planlog_set', to='company.plan'),
        ),
    ]
