# Generated by Django 3.2.12 on 2022-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_rule_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='resource',
            field=models.CharField(max_length=200),
        ),
    ]
